% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Jan-2026 12:06:43
%  MATLAB version: 25.2.0.2998904 (R2025b)
% -------------------------------------------------------------------
saveVarsMat = load('mesh_h3.mat');

msh = saveVarsMat.msh; % <1x1 struct> too many elements at msh.POS

clear saveVarsMat;
