% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Jun-2025 13:34:08
%  MATLAB version: 24.2.0.2740171 (R2024b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('mesh_h4.mat');

msh = saveVarsMat.msh; % <1x1 struct> too many elements at msh.POS

clear saveVarsMat;
