% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Feb-2026 14:25:19
%  MATLAB version: 25.2.0.2998904 (R2025b)
% -------------------------------------------------------------------
saveVarsMat = load('mesh_h4_H2.mat');

msh = saveVarsMat.msh; % <1x1 struct> too many elements at msh.POS

clear saveVarsMat;
