% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Feb-2026 11:58:12
%  MATLAB version: 25.2.0.2998904 (R2025b)
% -------------------------------------------------------------------
saveVarsMat = load('mesh_h5_H0.mat');

msh = saveVarsMat.msh; % <1x1 struct> too many elements at msh.POS

clear saveVarsMat;
