% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Jun-2025 11:03:46
%  MATLAB version: 24.2.0.2740171 (R2024b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('mesh_h6_H3.mat');

msh = saveVarsMat.msh; % <1x1 struct> too many elements at msh.POS

clear saveVarsMat;
